# Generated by Django 4.2.7 on 2024-12-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='carousel_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='products',
            name='full_description',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_slide1',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение Слайд-1'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_slide2',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение Слайд-2'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_slide3',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение Слайд-3'),
        ),
        migrations.AddField(
            model_name='products',
            name='mileage',
            field=models.PositiveIntegerField(default=0, verbose_name='Пробег (км)'),
        ),
    ]
